#!/usr/bin/env python3
"""
Generate a ProjectOverview.pptx describing the repo structure and flow.
Requires: python-pptx, graphviz (python package) and system graphviz for rendering DOT->PNG.
Run: pip install python-pptx graphviz
Then: python scripts/generate_pptx.py
Output: docs/ProjectOverview.pptx
"""
import json
import os
from pathlib import Path
from textwrap import shorten

try:
    from pptx import Presentation
    from pptx.util import Inches, Pt
except Exception:
    Presentation = None

try:
    import graphviz
except Exception:
    graphviz = None

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = PROJECT_ROOT / 'docs'
DOCS_DIR.mkdir(exist_ok=True)
OUTPUT_PPTX = DOCS_DIR / 'ProjectOverview.pptx'
FLOW_PNG = DOCS_DIR / 'flow_diagram.png'


def read_package_json():
    pkg = PROJECT_ROOT / 'package.json'
    if not pkg.exists():
        return {}
    return json.loads(pkg.read_text(encoding='utf-8'))


def build_folder_tree_text(root: Path, max_depth=3):
    lines = []
    root = root.resolve()
    def _walk(path, depth):
        if depth > max_depth:
            return
        for p in sorted(path.iterdir()):
            rel = p.relative_to(root)
            indent = '  ' * depth
            lines.append(f"{indent}- {rel.name}{'/' if p.is_dir() else ''}")
            if p.is_dir():
                _walk(p, depth+1)
    _walk(root, 0)
    return '\n'.join(lines)


def make_flow_diagram(dot_path: Path, out_png: Path):
    if graphviz is None:
        print('graphviz python package not installed; skipping diagram render')
        return False
    try:
        src = graphviz.Source(dot_path.read_text(encoding='utf-8'))
        src.format = 'png'
        src.render(str(out_png.with_suffix('')), cleanup=True)
        return True
    except Exception as e:
        print('Failed to render graphviz diagram:', e)
        return False


def create_pptx():
    if Presentation is None:
        print('python-pptx not installed. Install with: pip install python-pptx')
        return

    pkg = read_package_json()
    prs = Presentation()

    def _add_text_slide(title_text: str, body_text: str):
        # Try to use a common layout, but fall back to adding textboxes if placeholders are missing
        try:
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            try:
                slide.shapes.title.text = title_text
            except Exception:
                # create a title textbox
                title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.3), Inches(9), Inches(0.6))
                title_frame = title_box.text_frame
                title_frame.text = title_text
            try:
                tx = slide.shapes.placeholders[1].text_frame
                tx.clear()
                tx.text = body_text
            except Exception:
                # add a large textbox for body
                body_box = slide.shapes.add_textbox(Inches(0.5), Inches(1.2), Inches(9), Inches(5))
                body_box.text_frame.text = body_text
        except Exception:
            # ultimate fallback: blank layout and manual boxes
            slide = prs.slides.add_slide(prs.slide_layouts[6] if len(prs.slide_layouts) > 6 else prs.slide_layouts[0])
            title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.3), Inches(9), Inches(0.6))
            title_box.text_frame.text = title_text
            body_box = slide.shapes.add_textbox(Inches(0.5), Inches(1.2), Inches(9), Inches(5))
            body_box.text_frame.text = body_text

    # Title slide
    try:
        s = prs.slides.add_slide(prs.slide_layouts[0])
        try:
            s.shapes.title.text = pkg.get('name', 'Project')
        except Exception:
            tbox = s.shapes.add_textbox(Inches(0.5), Inches(0.5), Inches(9), Inches(1))
            tbox.text_frame.text = pkg.get('name', 'Project')
        try:
            s.placeholders[1].text = 'Project overview - Generated by script'
        except Exception:
            try:
                subtitle_box = s.shapes.add_textbox(Inches(0.5), Inches(1.2), Inches(9), Inches(0.6))
                subtitle_box.text_frame.text = 'Project overview - Generated by script'
            except Exception:
                pass
    except Exception:
        _add_text_slide(pkg.get('name', 'Project'), 'Project overview - Generated by script')

    # Summary slide
    tech = [
        f"React {pkg.get('dependencies', {}).get('react', '')}",
        f"Vite {pkg.get('devDependencies', {}).get('vite', '')}",
        f"TypeScript {pkg.get('devDependencies', {}).get('typescript', '')}",
        'react-three-fiber / drei / three (3D)'
    ]
    tech_text = 'Tech stack:\n' + '\n'.join(f"- {t}" for t in tech)
    _add_text_slide('High-level summary', tech_text)

    # Folder structure
    tree_text = build_folder_tree_text(PROJECT_ROOT, max_depth=2)
    _add_text_slide('Folder structure (top-level)', tree_text[:4000])

    # Entry points
    _add_text_slide('Entry points & App Flow', 'main.tsx -> App.tsx -> components (Navbar, Hero, TurfsSection, ... )')

    # Components slide
    comps = [
        'Navbar: top navigation',
        'Hero: landing section, lazy-loads 3D scene',
        'Hero3D: Canvas + lights, lazy loads AnimatedSphere',
        'AnimatedSphere: r3f/drei sphere animation',
        'TurfsSection: lists turfs',
        'TurfCard: single turf preview',
        'TurfDetails: details panel',
        'BookingModal: booking UI & WhatsApp integration',
        'Footer, AboutSection'
    ]
    _add_text_slide('Key components and responsibilities', '\n'.join(f"- {c}" for c in comps))

    # Data & assets slide
    data_files = [
        'src/data/turfs.json',
        'src/index.css',
        'index.html'
    ]
    _add_text_slide('Data & Assets', '\n'.join(f"- {f}" for f in data_files))

    # Build & scripts slide
    scripts = pkg.get('scripts', {})
    _add_text_slide('Build & scripts (package.json)', '\n'.join(f"- {k}: {v}" for k, v in scripts.items()))

    # 3D flow diagram slide
    try:
        slide = prs.slides.add_slide(prs.slide_layouts[5] if len(prs.slide_layouts) > 5 else prs.slide_layouts[1])
        try:
            slide.shapes.title.text = '3D component flow'
        except Exception:
            slide.shapes.add_textbox(Inches(0.5), Inches(0.3), Inches(9), Inches(0.6)).text_frame.text = '3D component flow'
        img_path = FLOW_PNG if FLOW_PNG.exists() else None
        if img_path:
            slide.shapes.add_picture(str(img_path), Inches(1), Inches(1.5), width=Inches(8))
        else:
            _add_text_slide('3D component flow', 'Flow: Hero -> Client3DLoader -> Hero3D -> AnimatedSphere -> three/drei/r3f')
    except Exception:
        _add_text_slide('3D component flow', 'Flow: Hero -> Client3DLoader -> Hero3D -> AnimatedSphere -> three/drei/r3f')

    # State flow slide
    _add_text_slide('App state flow', 'App holds: selectedTurfId, isDetailsOpen, isBookingOpen.\nTurfsSection -> TurfDetails -> BookingModal')

    # Next steps slide
    recs = [
        'Dependency hygiene: pin drei or upgrade React',
        'Bundle optimization: more lazy-loading',
        'Add tests & CI',
        'Lockfile & security audit'
    ]
    _add_text_slide('Next steps & recommendations', '\n'.join(f"- {r}" for r in recs))

    prs.save(str(OUTPUT_PPTX))
    print('Saved PPTX to', OUTPUT_PPTX)


if __name__ == '__main__':
    # try to create flow png from docs/flow.dot if present
    dot = DOCS_DIR / 'flow.dot'
    if dot.exists():
        ok = make_flow_diagram(dot, FLOW_PNG)
        if ok:
            print('Rendered flow diagram to', FLOW_PNG)
    create_pptx()
